### ISSUE TITLE
Place styles in JS

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/zoomhaus#6]
`npm i zoomhaus` doesn't work out-of-the-box because of missing styles - include those styles in the main js file?

**Comment by drewbaker** [comment]
That sounds unusual to include styles in a JS file. Is there a better way?

**Comment by johndigital** [comment]
Hmm, yea maybe there's an option in the configuration to automatically adds the styles? It definitely feels weird to do that in JS, but it's not super uncommon. Fitvids for instance just [injects a style declaration into the head](https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js#L21-L27).

Alternatively (or maybe in addition) we should make it easy to import the styles when you're in a module system; `import 'zoomhaus/styles.css'` or something like that.

In webpack that would just route the css to wherever you have it set up to go, bundling into build.css in vuepress for instance.

**Comment by SaFrMo** [comment]
Added this in 3.1.0 using [insert-css](https://www.npmjs.com/package/insert-css), which injects the default style in the head just like Fitvids. insert-css is pretty widely used and Zoomhaus depends really heavily on those styles, so it seemed like a fine place to mix CSS and JS.

You can add extra CSS with the `style` option on a new Zoomhaus instance, or set `style` to `false` to prevent any CSS injection.
